######################################################################
# Automatically generated by qmake (3.0) Wed Jul 17 11:14:22 2019
######################################################################

TEMPLATE = app
TARGET = qt.out
INCLUDEPATH += .
QT += gui widgets
# Input
SOURCES += main.cpp
SOURCES += mainwindow.cpp

 HEADERS += mainwindow.h