######################################################################
# Automatically generated by qmake (3.0) Wed Jul 17 11:14:22 2019
######################################################################

TEMPLATE = app
TARGET = qt.out
INCLUDEPATH += .
QT += gui widgets
# Input
SOURCES += main.cpp
SOURCES += mainwindow.cpp

 HEADERS += mainwindow.h

win32 {

}       
unix {
     
}
QMAKE_CXX = /usr/bin/g++

QMAKE_CXXFLAGS += -D_RELEASE_

QMAKE_LIBS += -L ./opt

#QMAKE_INCDIR_OPENGL_ES2